export const LOGIN_INIT = 'LOGIN_INIT'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGOUT = 'LOGOUT'

export const SIGN_UP_INIT = 'SIGN_UP_INIT'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const SIGNED_UP = 'SIGNED_UP'

export const UPDATING_PASSWORD = 'UPDATING_PASSWORD'
export const UPDATED_PASSWORD = 'UPDATED_PASSWORD'
export const UPDATED_PASSWORD_ERROR = 'UPDATED_PASSWORD_ERROR'

export const REQUESTING_PASSWORD_RESET = 'REQUESTING_PASSWORD_RESET'
export const REQUESTED_PASSWORD_RESET = 'REQUESTED_PASSWORD_RESET'
export const REQUESTED_PASSWORD_RESET_ERRORS = 'REQUESTED_PASSWORD_RESET_ERRORS'

export const CHANGING_PASSWORD = 'CHANGING_PASSWORD'
export const CHANGED_PASSWORD = 'CHANGED_PASSWORD'
export const CHANGED_PASSWORD_ERRORS = 'CHANGED_PASSWORD_ERRORS'

export const DELETE_ACCOUNT_INIT = 'DELETE_ACCOUNT_INIT'
export const DELETED_ACCOUNT = 'DELETED_ACCOUNT'

export const FACEBOOK_CONNECTED = 'FACEBOOK_CONNECTED'
export const EXISTING_FACEBOOK_USER = 'EXISTING_FACEBOOK_USER'
export const RETRY_FACEBOOK = 'RETRY_FACEBOOK'
export const FACEBOOK_FETCH_PAGE_INIT = 'FACEBOOK_FETCH_PAGE_INIT'
export const FACEBOOK_FETCHED_PAGE = 'FACEBOOK_FETCHED_PAGE'
export const FACEBOOK_RECONNECT = 'FACEBOOK_RECONNECT'

export const BILLING_FETCH_INIT = 'BILLING_FETCH_INIT'
export const BILLING_FETCHED = 'BILLING_FETCHED'

export const DOMAIN_FETCH_INIT = 'DOMAIN_FETCH_INIT'
export const DOMAIN_FETCHED = 'DOMAIN_FETCHED'

export const TLDS_FETCH_INIT = 'TLDS_FETCH_INIT'
export const TLDS_FETCHED = 'TLDS_FETCHED'

export const USER_PAGES_FETCH_INIT = 'USER_PAGES_FETCH_INIT'
export const USER_PAGES_FETCHED = 'USER_PAGES_FETCHED'

export const DOMAIN_REQUEST_INIT = 'DOMAIN_REQUEST_INIT'
export const DOMAIN_REQUESTED = 'DOMAIN_REQUESTED'

export const ADDING_DOMAIN = 'ADDING_DOMAIN'

export const UPGRADED = 'UPGRADED'
export const UPGRADING = 'UPGRADING'
export const UPGRADE_ERROR = 'UPGRADE_ERROR'

export const DIRECT_DEBIT_INIT = 'DIRECT_DEBIT_INIT'
export const COMPLETING_DIRECT_DEBIT_INIT = 'COMPLETING_DIRECT_DEBIT_INIT'

export const CARD_UPDATING = 'CARD_UPDATING'
export const CARD_UPDATED = 'CARD_UPDATED'
export const CARD_UPDATING_ERRORS = 'CARD_UPDATING_ERRORS'

export const PAGE_FETCH_INIT = 'PAGE_FETCH_INIT'
export const PAGE_FETCHED = 'PAGE_FETCHED'
export const PAGE_REFRESH_INIT = 'PAGE_REFRESH_INIT'
export const PAGE_REFRESHED = 'PAGE_REFRESHED'
export const PAGE_SYNCED = 'PAGE_SYNCED'
export const PAGE_EDITING = 'PAGE_EDITING'
export const SWITCH_CURRENT_PAGE = 'SWITCH_CURRENT_PAGE'
export const STATS_FETCHED = 'STATS_FETCHED'
export const STATS_FETCH_INIT = 'STATS_FETCH_INIT'
export const TOGGLING_PAGE_ONLINE = 'TOGGLING_PAGE_ONLINE'

export const ANALYTICS_SAVE_INIT = 'ANALYTICS_SAVE_INIT'
export const ANALYTICS_SAVED = 'ANALYTICS_SAVED'

export const THEMES_FETCH_INIT = 'THEMES_FETCH_INIT'
export const THEMES_FETCHED = 'THEMES_FETCHED'
export const ACTIVATE_THEME = 'ACTIVATE_THEME'
export const SAVE_SETTINGS = 'SAVE_SETTINGS'

export const HOME = 'HOME'
export const LOGIN = 'LOGIN'
